os: linux
dist: bionic
language: python
virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
    - xvfb
    - python-gi
    - python-gi-cairo
    - python3-gi
    - python3-gi-cairo
    - gir1.2-gtk-3.0

install:
- pip install --upgrade pip
- pip install -r requirements.txt

matrix:
  include:
  - name: "Python 3.6 Unit Tests"
    python: 3.6
    env: TEST_COMMAND=test
  - name: "Python 3.7 Unit Tests"
    python: 3.7
    env: TEST_COMMAND=test
  - name: "Python 3.8 Unit Tests"
    python: 3.8
    env: TEST_COMMAND=test
  - name: "Python Code Quality"
    python: 3.8
    env: TEST_COMMAND=flake8

script:
- xvfb-run coverage run setup.py $TEST_COMMAND

after_success:
- test $TEST_COMMAND = "test" && coveralls
